// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engines.sql

package dbgen

import (
	"context"
)

const listEngines = `-- name: ListEngines :many

SELECT id, name, url_tpl, icon_text, icon_color, sort_order, is_builtin FROM engines ORDER BY sort_order, id
`

// engines.sql - search engines (keep this file pure ASCII, see 001_init.sql header)
func (q *Queries) ListEngines(ctx context.Context) ([]Engine, error) {
	rows, err := q.db.QueryContext(ctx, listEngines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Engine{}
	for rows.Next() {
		var i Engine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UrlTpl,
			&i.IconText,
			&i.IconColor,
			&i.SortOrder,
			&i.IsBuiltin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
