// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package dbgen

import (
	"context"
)

const createFolder = `-- name: CreateFolder :exec

INSERT INTO folders (id, name, size) VALUES (?, ?, ?)
`

type CreateFolderParams struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
	Size int64   `json:"size"`
}

// folders.sql - folder CRUD (keep this file pure ASCII, see 001_init.sql header)
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) error {
	_, err := q.db.ExecContext(ctx, createFolder, arg.ID, arg.Name, arg.Size)
	return err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = ?
`

func (q *Queries) DeleteFolder(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, id)
	return err
}

const listEmptyFoldersForPage = `-- name: ListEmptyFoldersForPage :many
SELECT f.id FROM folders f
JOIN placements p ON p.folder_id = f.id
WHERE p.page_id = ?
  AND NOT EXISTS (SELECT 1 FROM placements c WHERE c.in_folder = f.id)
`

// Folders that hold no items - used to enforce "empty folders are deleted".
func (q *Queries) ListEmptyFoldersForPage(ctx context.Context, pageID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEmptyFoldersForPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersForPage = `-- name: ListFoldersForPage :many
SELECT f.id, f.name, f.size, f.created_at FROM folders f
JOIN placements p ON p.folder_id = f.id
WHERE p.page_id = ?
`

func (q *Queries) ListFoldersForPage(ctx context.Context, pageID string) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersForPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolder = `-- name: UpdateFolder :exec
UPDATE folders SET name = ?, size = ? WHERE id = ?
`

type UpdateFolderParams struct {
	Name *string `json:"name"`
	Size int64   `json:"size"`
	ID   string  `json:"id"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) error {
	_, err := q.db.ExecContext(ctx, updateFolder, arg.Name, arg.Size, arg.ID)
	return err
}
