// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

type Engine struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	UrlTpl    string `json:"url_tpl"`
	IconText  string `json:"icon_text"`
	IconColor string `json:"icon_color"`
	SortOrder int64  `json:"sort_order"`
	IsBuiltin int64  `json:"is_builtin"`
}

type Folder struct {
	ID        string  `json:"id"`
	Name      *string `json:"name"`
	Size      int64   `json:"size"`
	CreatedAt string  `json:"created_at"`
}

type Link struct {
	ID            string  `json:"id"`
	Title         string  `json:"title"`
	Url           string  `json:"url"`
	OpenNewTab    int64   `json:"open_new_tab"`
	IconSource    string  `json:"icon_source"`
	IconPath      *string `json:"icon_path"`
	IconMime      *string `json:"icon_mime"`
	IconW         *int64  `json:"icon_w"`
	IconH         *int64  `json:"icon_h"`
	IconStatus    string  `json:"icon_status"`
	IconCheckedAt *string `json:"icon_checked_at"`
	MonoText      *string `json:"mono_text"`
	MonoColor     string  `json:"mono_color"`
	MonoFontSize  int64   `json:"mono_font_size"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type Page struct {
	ID            string  `json:"id"`
	Slug          string  `json:"slug"`
	Name          string  `json:"name"`
	SortOrder     int64   `json:"sort_order"`
	Revision      int64   `json:"revision"`
	WallpaperMode string  `json:"wallpaper_mode"`
	WallpaperID   *string `json:"wallpaper_id"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type Placement struct {
	ID        string  `json:"id"`
	PageID    string  `json:"page_id"`
	FolderID  *string `json:"folder_id"`
	LinkID    *string `json:"link_id"`
	InFolder  *string `json:"in_folder"`
	Col       int64   `json:"col"`
	Row       int64   `json:"row"`
	SortOrder int64   `json:"sort_order"`
}

type Setting struct {
	K string `json:"k"`
	V string `json:"v"`
}

type Wallpaper struct {
	ID        string  `json:"id"`
	Kind      string  `json:"kind"`
	RemoteUrl *string `json:"remote_url"`
	File      *string `json:"file"`
	ThumbFile *string `json:"thumb_file"`
	W         *int64  `json:"w"`
	H         *int64  `json:"h"`
	Bytes     *int64  `json:"bytes"`
	SortOrder int64   `json:"sort_order"`
	CreatedAt string  `json:"created_at"`
}
