// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package dbgen

import (
	"context"
)

const bumpPageRevision = `-- name: BumpPageRevision :one
UPDATE pages
SET revision = revision + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = ?
RETURNING revision
`

func (q *Queries) BumpPageRevision(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpPageRevision, id)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const countPages = `-- name: CountPages :one
SELECT COUNT(*) FROM pages
`

func (q *Queries) CountPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :exec
INSERT INTO pages (id, slug, name, sort_order, wallpaper_mode, wallpaper_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePageParams struct {
	ID            string  `json:"id"`
	Slug          string  `json:"slug"`
	Name          string  `json:"name"`
	SortOrder     int64   `json:"sort_order"`
	WallpaperMode string  `json:"wallpaper_mode"`
	WallpaperID   *string `json:"wallpaper_id"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) error {
	_, err := q.db.ExecContext(ctx, createPage,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.SortOrder,
		arg.WallpaperMode,
		arg.WallpaperID,
	)
	return err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = ?
`

func (q *Queries) DeletePage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePage, id)
	return err
}

const getPage = `-- name: GetPage :one
SELECT id, slug, name, sort_order, revision, wallpaper_mode, wallpaper_id, created_at, updated_at FROM pages WHERE id = ?
`

func (q *Queries) GetPage(ctx context.Context, id string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPage, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SortOrder,
		&i.Revision,
		&i.WallpaperMode,
		&i.WallpaperID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, slug, name, sort_order, revision, wallpaper_mode, wallpaper_id, created_at, updated_at FROM pages WHERE slug = ?
`

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SortOrder,
		&i.Revision,
		&i.WallpaperMode,
		&i.WallpaperID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPages = `-- name: ListPages :many

SELECT id, slug, name, sort_order, revision, wallpaper_mode, wallpaper_id, created_at, updated_at FROM pages ORDER BY sort_order, id
`

// pages.sql - page CRUD (keep this file pure ASCII, see 001_init.sql header)
func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SortOrder,
			&i.Revision,
			&i.WallpaperMode,
			&i.WallpaperID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxPageSortOrder = `-- name: MaxPageSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) AS max_sort_order FROM pages
`

func (q *Queries) MaxPageSortOrder(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxPageSortOrder)
	var max_sort_order interface{}
	err := row.Scan(&max_sort_order)
	return max_sort_order, err
}

const updatePage = `-- name: UpdatePage :exec
UPDATE pages
SET name = ?, slug = ?, wallpaper_mode = ?, wallpaper_id = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = ?
`

type UpdatePageParams struct {
	Name          string  `json:"name"`
	Slug          string  `json:"slug"`
	WallpaperMode string  `json:"wallpaper_mode"`
	WallpaperID   *string `json:"wallpaper_id"`
	ID            string  `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.ExecContext(ctx, updatePage,
		arg.Name,
		arg.Slug,
		arg.WallpaperMode,
		arg.WallpaperID,
		arg.ID,
	)
	return err
}

const updatePageSortOrder = `-- name: UpdatePageSortOrder :exec
UPDATE pages
SET sort_order = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = ?
`

type UpdatePageSortOrderParams struct {
	SortOrder int64  `json:"sort_order"`
	ID        string `json:"id"`
}

func (q *Queries) UpdatePageSortOrder(ctx context.Context, arg UpdatePageSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updatePageSortOrder, arg.SortOrder, arg.ID)
	return err
}
