// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	BumpPageRevision(ctx context.Context, id string) (int64, error)
	CountPages(ctx context.Context) (int64, error)
	CountPlacementsInFolder(ctx context.Context, inFolder *string) (int64, error)
	// folders.sql - folder CRUD (keep this file pure ASCII, see 001_init.sql header)
	CreateFolder(ctx context.Context, arg CreateFolderParams) error
	CreateLink(ctx context.Context, arg CreateLinkParams) error
	CreatePage(ctx context.Context, arg CreatePageParams) error
	CreatePlacement(ctx context.Context, arg CreatePlacementParams) error
	DeleteFolder(ctx context.Context, id string) error
	DeleteLink(ctx context.Context, id string) error
	DeletePage(ctx context.Context, id string) error
	DeletePlacementsForPage(ctx context.Context, pageID string) error
	GetLink(ctx context.Context, id string) (Link, error)
	GetPage(ctx context.Context, id string) (Page, error)
	GetPageBySlug(ctx context.Context, slug string) (Page, error)
	ListAllLinksWithPage(ctx context.Context) ([]ListAllLinksWithPageRow, error)
	// Folders that hold no items - used to enforce "empty folders are deleted".
	ListEmptyFoldersForPage(ctx context.Context, pageID string) ([]string, error)
	// engines.sql - search engines (keep this file pure ASCII, see 001_init.sql header)
	ListEngines(ctx context.Context) ([]Engine, error)
	ListFoldersForPage(ctx context.Context, pageID string) ([]Folder, error)
	// links.sql - link CRUD (keep this file pure ASCII, see 001_init.sql header)
	ListLinks(ctx context.Context) ([]Link, error)
	ListLinksForPage(ctx context.Context, pageID string) ([]Link, error)
	// pages.sql - page CRUD (keep this file pure ASCII, see 001_init.sql header)
	ListPages(ctx context.Context) ([]Page, error)
	// placements.sql - board placement CRUD (keep this file pure ASCII, see 001_init.sql header)
	ListPlacementsForPage(ctx context.Context, pageID string) ([]Placement, error)
	// settings.sql - key/value settings (keep this file pure ASCII, see 001_init.sql header)
	ListSettings(ctx context.Context) ([]Setting, error)
	MaxPageSortOrder(ctx context.Context) (interface{}, error)
	UpdateFolder(ctx context.Context, arg UpdateFolderParams) error
	UpdateLink(ctx context.Context, arg UpdateLinkParams) error
	UpdatePage(ctx context.Context, arg UpdatePageParams) error
	UpdatePageSortOrder(ctx context.Context, arg UpdatePageSortOrderParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
