// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"
)

const listSettings = `-- name: ListSettings :many

SELECT k, v FROM settings
`

// settings.sql - key/value settings (keep this file pure ASCII, see 001_init.sql header)
func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.K, &i.V); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (k, v) VALUES (?, ?)
ON CONFLICT(k) DO UPDATE SET v = excluded.v
`

type UpsertSettingParams struct {
	K string `json:"k"`
	V string `json:"v"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.K, arg.V)
	return err
}
