// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallpapers.sql

package dbgen

import (
	"context"
)

const countWallpapersByFile = `-- name: CountWallpapersByFile :one
SELECT COUNT(*) FROM wallpapers WHERE file = ?
`

func (q *Queries) CountWallpapersByFile(ctx context.Context, file *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWallpapersByFile, file)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWallpapersByThumb = `-- name: CountWallpapersByThumb :one
SELECT COUNT(*) FROM wallpapers WHERE thumb_file = ?
`

func (q *Queries) CountWallpapersByThumb(ctx context.Context, thumbFile *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWallpapersByThumb, thumbFile)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWallpaper = `-- name: CreateWallpaper :exec
INSERT INTO wallpapers (id, kind, remote_url, file, thumb_file, w, h, bytes, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWallpaperParams struct {
	ID        string  `json:"id"`
	Kind      string  `json:"kind"`
	RemoteUrl *string `json:"remote_url"`
	File      *string `json:"file"`
	ThumbFile *string `json:"thumb_file"`
	W         *int64  `json:"w"`
	H         *int64  `json:"h"`
	Bytes     *int64  `json:"bytes"`
	SortOrder int64   `json:"sort_order"`
}

func (q *Queries) CreateWallpaper(ctx context.Context, arg CreateWallpaperParams) error {
	_, err := q.db.ExecContext(ctx, createWallpaper,
		arg.ID,
		arg.Kind,
		arg.RemoteUrl,
		arg.File,
		arg.ThumbFile,
		arg.W,
		arg.H,
		arg.Bytes,
		arg.SortOrder,
	)
	return err
}

const deleteWallpaper = `-- name: DeleteWallpaper :exec
DELETE FROM wallpapers WHERE id = ?
`

func (q *Queries) DeleteWallpaper(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWallpaper, id)
	return err
}

const getWallpaper = `-- name: GetWallpaper :one
SELECT id, kind, remote_url, file, thumb_file, w, h, bytes, sort_order, created_at FROM wallpapers WHERE id = ?
`

func (q *Queries) GetWallpaper(ctx context.Context, id string) (Wallpaper, error) {
	row := q.db.QueryRowContext(ctx, getWallpaper, id)
	var i Wallpaper
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RemoteUrl,
		&i.File,
		&i.ThumbFile,
		&i.W,
		&i.H,
		&i.Bytes,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listWallpapers = `-- name: ListWallpapers :many

SELECT id, kind, remote_url, file, thumb_file, w, h, bytes, sort_order, created_at FROM wallpapers ORDER BY sort_order, created_at
`

// wallpapers.sql - wallpapers (keep this file pure ASCII, see 001_init.sql header)
func (q *Queries) ListWallpapers(ctx context.Context) ([]Wallpaper, error) {
	rows, err := q.db.QueryContext(ctx, listWallpapers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallpaper{}
	for rows.Next() {
		var i Wallpaper
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.RemoteUrl,
			&i.File,
			&i.ThumbFile,
			&i.W,
			&i.H,
			&i.Bytes,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materializeWallpaper = `-- name: MaterializeWallpaper :exec
UPDATE wallpapers
SET kind = 'upload', file = ?, thumb_file = ?, w = ?, h = ?, bytes = ?
WHERE id = ?
`

type MaterializeWallpaperParams struct {
	File      *string `json:"file"`
	ThumbFile *string `json:"thumb_file"`
	W         *int64  `json:"w"`
	H         *int64  `json:"h"`
	Bytes     *int64  `json:"bytes"`
	ID        string  `json:"id"`
}

func (q *Queries) MaterializeWallpaper(ctx context.Context, arg MaterializeWallpaperParams) error {
	_, err := q.db.ExecContext(ctx, materializeWallpaper,
		arg.File,
		arg.ThumbFile,
		arg.W,
		arg.H,
		arg.Bytes,
		arg.ID,
	)
	return err
}

const maxWallpaperSortOrder = `-- name: MaxWallpaperSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) AS max_sort_order FROM wallpapers
`

func (q *Queries) MaxWallpaperSortOrder(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxWallpaperSortOrder)
	var max_sort_order interface{}
	err := row.Scan(&max_sort_order)
	return max_sort_order, err
}

const updateWallpaperMeta = `-- name: UpdateWallpaperMeta :exec
UPDATE wallpapers SET sort_order = ?, remote_url = ? WHERE id = ?
`

type UpdateWallpaperMetaParams struct {
	SortOrder int64   `json:"sort_order"`
	RemoteUrl *string `json:"remote_url"`
	ID        string  `json:"id"`
}

func (q *Queries) UpdateWallpaperMeta(ctx context.Context, arg UpdateWallpaperMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateWallpaperMeta, arg.SortOrder, arg.RemoteUrl, arg.ID)
	return err
}
